package com.heritage.registration.valueobject;

public enum RequestStatus {
	ACTIVE,
	WAITING_VERIFICATION,
	WAITING_DISABLE_VERIFICATION,
	WAITING_REPAIR,
	DISABLED,
	LOCKED,
	CREATED,
	VALIDATION_ERROR,
	SUBMITTED,
	REJECTED,
	EXCEPTIONAL,
	WAITING_APPROVAL,
	CBS_INTEGRATION_FAILED,
	DELETED,
	DUPLICATE,
	POST_DATED
}
