/**
 * Heritage service API
 * Heritage service API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BioData {
    firstName?: string;
    middleName?: string;
    lastName?: string;
    kindred?: string;
    village?: string;
    community?: string;
    town?: string;
    lga?: string;
    state?: string;
    dob?: string;
    disabled?: boolean;
    maritalStatus?: BioData.MaritalStatusEnum;
    sex?: BioData.SexEnum;
}

export namespace BioData {
    export type MaritalStatusEnum = 'SINGLE' | 'MARRIED' | 'DIVORCED';
    export const MaritalStatusEnum = {
        SINGLE: 'SINGLE' as MaritalStatusEnum,
        MARRIED: 'MARRIED' as MaritalStatusEnum,
        DIVORCED: 'DIVORCED' as MaritalStatusEnum
    };
    export type SexEnum = 'MALE' | 'FEMALE';
    export const SexEnum = {
        MALE: 'MALE' as SexEnum,
        FEMALE: 'FEMALE' as SexEnum
    };
}


