/**
 * Heritage service API
 * Heritage service API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SchoolType = 'UNIVERSITY' | 'POLYTECHNIC' | 'COLLEGE_OF_EDUCATION';

export const SchoolType = {
    UNIVERSITY: 'UNIVERSITY' as SchoolType,
    POLYTECHNIC: 'POLYTECHNIC' as SchoolType,
    COLLEGEOFEDUCATION: 'COLLEGE_OF_EDUCATION' as SchoolType
};

