/**
 * Heritage service API
 * Heritage service API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {SubjectResponse} from './subject-response';
import {BioData} from './bio-data';
import {Course} from './course';


export interface StudentRegistrationFilterRequest {
    bioData?: BioData;
    subjects?: Array<SubjectResponse>;
    schoolsAttended?: Array<SubjectResponse>;
    coursesToStudy?: Array<Course>;
    uuid?: string;
    status?: string;
    enable?: boolean;
}

