/**
 * Heritage service API
 * Heritage service API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageModel} from './page-model';
import {StudentRegistrationResponse} from './student-registration-response';


export interface StudentRegistrationResponsePage {
    content?: Array<StudentRegistrationResponse>;
    pageInfo?: PageModel;
}

