/**
 * Heritage service API
 * Heritage service API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {WorkflowActionResponse} from './workflow-action-response';


export interface SubjectResponse {
    code?: string;
    name?: string;
    shortName?: string;
    uuid?: string;
    availableActions?: Array<WorkflowActionResponse>;
    href?: string;
    status?: string;
    enable?: boolean;
}

